# Generated by Django 3.1.6 on 2021-02-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20210215_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='test_id',
            new_name='test',
        ),
    ]
